changes to wm

diff --git a/bin/sport b/bin/sport
--- a/bin/sport
+++ b/bin/sport
@@ -1,19 +1,59 @@
 #! /bin/sh
-ifreset=$1
-if [ "$ifreset" == "reset" ]
-then
-    killall zoom 2>/dev/null
-    killall vlc 2>/dev/null
+function usage {
+    echo "Usage: $(basename $0) [-acemov]" 2>&1
+    echo '   -e   End sport session'
+    echo '   -r   Reset sport session'
+    echo '   -s   Start sport session'
+    exit 1
+}
+if [[ ${#} -eq 0 ]]; then
+    usage
+fi
+ifReset=false
+ifStart=false
+ifEnd=false
+while getopts ehrs  o
+do
+    case "$o" in
+        e) ifEnd=true;;
+        r) ifRestart=true;;
+        s) ifStart=true;;
+        h) usage; exit 1;;
+        \?) echo "Error! -$OPTARG"; exit 1;;
+    esac
+done
+if $ifReset || $ifEnd; then
+        killall zoom 2>/dev/null
+        killall vlc 2>/dev/null
 fi
 
-xrandr --output HDMI1 --left-of eDP1
+if $ifReset || $ifStart; then
+    xrandr --output HDMI1 --auto
+    xrandr --output HDMI1 --left-of eDP1
+    HDMISound="alsa_output.pci-0000_00_1f.3-platform-skl_hda_dsp_generic.HiFi__hw_sofhdadsp_3__sink"
+    pactl set-default-sink $HDMISound
+    if [ -z "$(pidof vlc)" ] 
+    then
+        vlc &
+    fi
 
-if [ -z "$(pidof vlc)" ] 
-then
-    vlc &
+    if [ -z "$(pidof zoom)" ] 
+    then
+        zoom &
+    fi
+#     i3-msg "[workspace=1]" move workspace to output HDMI1
+#     i3-msg "[workspace=2]" move workspace to output eDP1
+sleep 1
+    mvws 1 HDMI1
+    mvws 2 eDP1
 fi
 
-if [ -z "$(pidof zoom)" ] 
-then
-    zoom &
+if $ifEnd; then
+    LaptopSound="alsa_output.pci-0000_00_1f.3-platform-skl_hda_dsp_generic.HiFi__hw_sofhdadsp__sink"
+    pactl set-default-sink $LaptopSound
+#     xrandr --output HDMI1 --off
+    for i in {1..10}; 
+    do 
+        mvws $i eDP1 > /dev/null
+    done
 fi
